[phases.setup]
  aptPkgs = [
    'fonts-liberation',
    'libappindicator3-1',
    'libasound2t64',
    'libatk-bridge2.0-0',
    'libatk1.0-0',
    'libgbm-dev',
    'libgtk-3-0',
    'libnspr4',
    'libx11-xcb1',
    'libxcomposite1',
    'libxcursor1',
    'libxdamage1',
    'libxfixes3',
    'libxi6',
    'libxrandr2',
    'libxss1',
    'libxtst6',
    'xdg-utils',
    'libdbus-1-3',
    'libxkbcommon-dev',
    'binutils',
    'libglib2.0-0',
    'libgdk-pixbuf2.0-0',
    'libnss3-dev',
    'libxss-dev',
    'xvfb',
    'libu2f-udev',
    ]
