import { htmlToText } from "html-to-text";

export function flattenHTML(html: string) {
  return htmlToText(html, {
    wordwrap: 130,
    selectors: [
      { selector: "a", options: { ignoreHref: true } },
      { selector: "img", format: "skip" },
      { selector: "nav", format: "skip" },
      { selector: "footer", format: "skip" },
      { selector: "header", format: "skip" },
      { selector: "aside", format: "skip" },
      { selector: "form", format: "skip" },
      { selector: "input", format: "skip" },
      { selector: "button", format: "skip" },
      // Common advertising and tracking elements
      { selector: ".ad", format: "skip" },
      { selector: ".advertisement", format: "skip" },
      { selector: ".ads", format: "skip" },
      { selector: ".banner", format: "skip" },
      { selector: ".cookie-notice", format: "skip" },
      { selector: ".cookie-banner", format: "skip" },
      { selector: ".newsletter", format: "skip" },
      { selector: ".popup", format: "skip" },
      { selector: ".modal", format: "skip" },
      { selector: ".overlay", format: "skip" },
      { selector: ".sidebar", format: "skip" },
      { selector: ".breadcrumb", format: "skip" },
      { selector: ".pagination", format: "skip" },
      { selector: ".social-share", format: "skip" },
      { selector: ".social-media", format: "skip" },
      { selector: ".related-posts", format: "skip" },
      { selector: ".recommendations", format: "skip" },
      { selector: ".comments", format: "skip" },
      { selector: ".comment-section", format: "skip" },
      { selector: ".rating", format: "skip" },
      { selector: ".reviews", format: "skip" },
      { selector: ".share", format: "skip" },
      { selector: ".print", format: "skip" },
      { selector: ".back-to-top", format: "skip" },
      { selector: ".scroll-to-top", format: "skip" },
      { selector: ".loading", format: "skip" },
      { selector: ".spinner", format: "skip" },
      { selector: ".loader", format: "skip" },
    ],
  });
}
